// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: url.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (code, original_url) VALUES ($1, $2)
RETURNING id, code, original_url, created_at
`

type CreateURLParams struct {
	Code        string `json:"code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.Code, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getURLByCode = `-- name: GetURLByCode :one
SELECT id, code, original_url, created_at FROM urls WHERE code = $1
`

func (q *Queries) GetURLByCode(ctx context.Context, code string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByCode, code)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}
